### ISSUE TITLE
工作学习卡片

### ISSUE THREAD

**Issue by violettianjie** [violettianjie/hello-world#1]
# 术语卡 敏捷开发

2001年被提出。和瀑布开发不一样。

是否文档更少？但还是需要需求文档吧？

**Comment by violettianjie** [comment]
## 术语卡 精益画布
lean canvas

一种表述创业项目的方法。
分为9个部分。

**Comment by marcia5** [comment]
hi

**Comment by liqunfang** [comment]
heklo qunfang

**Comment by violettianjie** [comment]
# 任意卡

- 大家可以在这里讨论一个问题。比如 昨天活动的心得分享。哈哈。

**Comment by violettianjie** [comment]
## 术语卡 雷达RADAR

- 雷达： 无线电侦测和定距的简称

- The term RADAR was coined in 1940 by the United States Navy as an acronym for **RAdio Detection And Ranging**  or RAdio Direction And Ranging.The term radar has since entered English and other languages as a common noun, losing all capitalization.

- 出处[维基百科](https://en.wikipedia.org/wiki/Radar)

**Comment by violettianjie** [comment]
## 术语卡 阵列天线 array antenna

- 许多相同的单个天线(如对称天线)按一定规律排列组成的天线系统
- [出处 维基百科](https://en.wikipedia.org/wiki/Antenna_array)

**Comment by violettianjie** [comment]
## 术语卡 商业智能BI

- 术语  **BI** （Business Intelligence ）:Business Intelligence (BI) are the set of strategies, processes, applications, data, technologies and technical architectures which are used to support the collection, analysis, presentation and dissemination of business information.

- 历史： 1865年首次使用这个词汇。
    1865年，被首次提出这个词。
The earliest known use of the term "Business Intelligence" is in Richard Millar Devens’ in the ‘Cyclopædia of Commercial and Business Anecdotes’ from 1865. Devens used the term to describe how the banker, Sir Henry Furnese, gained profit by receiving and acting upon information about his environment, prior to his competitors. “Throughout Holland, Flanders, France, and Germany, he maintained a complete and perfect train of business intelligence. The news of the many battles fought was thus received first by him, and the fall of Namur added to his profits, owing to his early receipt of the news.” (Devens, (1865), p. 210). The ability to collect and react accordingly based on the information retrieved, an ability that Furnese excelled in, is today still at the very heart of BI.

   1958年，IBM研究者Peter Luhn  使用了这个词。
In a 1958 article, IBM researcher Hans Peter Luhn used the term business intelligence. He employed the Webster's dictionary definition of intelligence: "the ability to apprehend the interrelationships of presented facts in such a way as to guide action towards a desired goal."

   19世纪80年代， 商业智能被用于 1960s 提出的DSS 决策支持系统。
Business intelligence as it is understood today is said to have evolved from the decision support systems (DSS) that began in the 1960s and developed throughout the mid-1980s. DSS originated in the computer-aided models created to assist with decision making and planning. From DSS, data warehouses, Executive Information Systems, OLAP and business intelligence came into focus beginning in the late 80s.
  - BI 和数据仓库不是一回事。可以BI 不用数据仓库，也可以数据仓库不用BI。数据仓库技术可以服务于商业智能

  - [出处](https://en.wikipedia.org/wiki/Business_intelligence)

**Comment by violettianjie** [comment]
## 术语卡  数据仓库

- 术语  data warehousing

- 历史 The concept of data warehousing dates back to the late 1980s when IBM researchers Barry Devlin and Paul Murphy developed the "business data warehouse". 

- 
1960s – General Mills and Dartmouth College, in a joint research project, develop the terms dimensions and facts.
1970s – ACNielsen and IRI provide dimensional data marts for retail sales.
1970s – Bill Inmon begins to define and discuss the term: Data Warehouse.

- [出处](https://en.wikipedia.org/wiki/Data_warehouse)

- 相关概念： 数据集市、ETL 

![Uploading image.png…]()

**Comment by violettianjie** [comment]
## 反常识卡 

- 反常识：  Hadoop 现在不能代替数据仓库，未来也许会。

- 常识 ： Hadoop可以代替昂贵的数据仓库产品

- 例子：Hadoop还只是数据仓库产品的一个补充，和数据仓库一起构建混搭架构为上层应用联合提供服务。

> 我们相信在数据仓库市场Hadoop会迟早替代到现在的产品，只不过，那时候的Hadoop已经又不是现在的样子了。——[Mike Stonebroker
](https://en.wikipedia.org/wiki/Michael_Stonebraker)

## 金句卡

> 你千万不要想着拿数据去改进一个业务，这不是大数据。你一定是去做了一件以前做不了的事情。
   -王坚

**Comment by violettianjie** [comment]
## 术语卡 数据库 database

- [出处](https://en.wikipedia.org/wiki/Database)

- 与DBMS （数据库管理系统）的区别：后者是应用程序。
   A database management system (DBMS) is a computer software application that interacts with the user, other applications, and the database itself to capture and analyze data. A general-purpose DBMS is designed to allow the definition, creation, querying, update, and administration of databases.

-  [NoSQL](https://en.wikipedia.org/wiki/NoSQL): 1998年被提出。Hbase 就是NoSQL 中的基于列的数据库。

- 相关概念： OLTP 联机事务处理on-line transaction processing 传统关系型数据库；
                      OLAP 联机分析处理 On-Line Analytical Processing：数据仓库中应用

**Comment by violettianjie** [comment]
## 人名卡  

- 人名 Hedy Lamarr （9 November 1914 – 19 January 2000）。入美国籍犹太人。

- 印象： 演员，发明家， CDMA 之母。6次不幸婚姻，晚年独身30余年。居然是一个演员的发明，改变了我们的通信。用手机时，应该感谢这位美女。这点，太惊讶了。音乐和技术某种意义上真是相通的，而智慧与美貌一身的人，并不见得生前得到认可和幸福。

- 例子： 从钢琴曲中得到灵感，发明频谱（spectrum），为CDMA 作下巨大贡献。生前未得到认可。
  

- [出处](https://en.wikipedia.org/wiki/Hedy_Lamarr)

> At the beginning of World War II, Lamarr and composer George Antheil developed a radio guidance system for Allied torpedoes, which used spread spectrum and frequency hopping technology to defeat the threat of jamming by the Axis powers.Although the US Navy did not adopt the technology until the 1960s, the principles of their work are now incorporated into modern Wi-Fi, CDMA, and Bluetooth technology,[5][6][7] and this work led to their induction into the National Inventors Hall of Fame in 2014.

**Comment by violettianjie** [comment]
##  3G

- [出处](https://en.wikipedia.org/wiki/3G)
### 分类

1. the UMTS (Universal Mobile Telecommunications Service) system, first offered in 2001, standardized by 3GPP, used primarily in Europe, Japan, China (however with a different radio interface) and other regions predominated by GSM (Global Systems for Mobile) 2G system infrastructure. The cell phones are typically UMTS and GSM hybrids. Several radio interfaces are offered, sharing the same infrastructure: 
The original and most widespread radio interface is called W-CDMA (Wideband Code Division Multiple Access).

** The TD-SCDMA radio interface was commercialized in 2009 and is only offered in China.** 

TD-SCDMA 只是在中国商业化

The latest UMTS release, HSPA+, can provide peak data rates up to 56 Mbit/s in the downlink in theory (28 Mbit/s in existing services) and 22 Mbit/s in the uplink.
the CDMA2000 system, first offered in 2002, standardized by 3GPP2, used especially in North America and South Korea, sharing infrastructure with the IS-95 2G standard. The cell phones are typically CDMA2000 and IS-95 hybrids. The latest release EVDO Rev B offers peak rates of 14.7 Mbit/s downstream.
The above systems and radio interfaces are based on spread spectrum radio transmission technology. While the GSM EDGE standard ("2.9G"), DECT cordless phones and Mobile WiMAX standards formally also fulfill the IMT-2000 requirements and are approved as 3G standards by ITU, these are typically not branded 3G, and are based on completely different technologies.


The following common standards comply with the IMT2000/3G standard:

2、EDGE, a revision by the 3GPP organization to the older 2G GSM based transmission methods, utilizing the same switching nodes, base station sites and frequencies as GPRS, but new base station and cellphone RF circuits. It is based on the three times as efficient 8PSK modulation scheme as supplement to the original GMSK modulation scheme. EDGE is still used extensively due to its ease of upgrade from existing 2G GSM infrastructure and cell-phones. 
EDGE combined with the GPRS 2.5G technology is called EGPRS, and allows peak data rates in the order of 200 kbit/s, just as the original UMTS WCDMA versions, and thus formally fulfills the IMT2000 requirements on 3G systems. However, in practice EDGE is seldom marketed as a 3G system, but a 2.9G system. EDGE shows slightly better system spectral efficiency than the original UMTS and CDMA2000 systems, but it is difficult to reach much higher peak data rates due to the limited GSM spectral bandwidth of 200 kHz, and it is thus a dead end.
EDGE was also a mode in the IS-135 TDMA system, today ceased.
Evolved EDGE, the latest revision, has peaks of 1 Mbit/s downstream and 400 kbit/s upstream, but is not commercially used.

3、The Universal Mobile Telecommunications System, created and revised by the 3GPP. The family is a full revision from GSM in terms of encoding methods and hardware, although some GSM sites can be retrofitted to broadcast in the UMTS/W-CDMA format. 
W-CDMA is the most common deployment, commonly operated on the 2,100 MHz band. A few others use the 850, 900 and 1,900 MHz bands. 
HSPA is an amalgamation of several upgrades to the original W-CDMA standard and offers speeds of 14.4 Mbit/s down and 5.76 Mbit/s up. HSPA is backward-compatible with and uses the same frequencies as W-CDMA.
HSPA+, a further revision and upgrade of HSPA, can provide theoretical peak data rates up to 168 Mbit/s in the downlink and 22 Mbit/s in the uplink, using a combination of air interface improvements as well as multi-carrier HSPA and MIMO. Technically though, MIMO and DC-HSPA can be used without the "+" enhancements of HSPA+
The CDMA2000 system, or IS-2000, including CDMA2000 1x and CDMA2000 High Rate Packet Data (or EVDO), standardized by 3GPP2 (differing from the 3GPP), evolving from the original IS-95 CDMA system, is used especially in North America, China, India, Pakistan, Japan, South Korea, Southeast Asia, Europe and Africa. 
CDMA2000 1x Rev. E has an increased voice capacity (in excess of three times) compared to Rev. 0 EVDO Rev. B offers downstream peak rates of 14.7 Mbit/s while Rev. C enhanced existing and new terminal user experience.
While DECT cordless phones and Mobile WiMAX standards formally also fulfill the IMT-2000 requirements, they are not usually considered due to their rarity and unsuitability for usage with mobile phones.

**Comment by violettianjie** [comment]
## 术语卡 band
- LTE频段  [frequency band](https://en.wikipedia.org/wiki/LTE_frequency_bands)

- LTE 网络亚洲 列表 [维基](https://en.wikipedia.org/wiki/List_of_LTE_networks_in_Asia)

- band 40  联通 移动 电信 都有。

**Comment by violettianjie** [comment]
## 术语卡 AUDS 反无人机防御系统

- 术语   AUDS (Anti-UAV Defence System) 

- unmanned aerial vehicles (UAVs),

**Comment by violettianjie** [comment]
##  书名卡 《大教堂与集市》

- 印象 ：互联网时代的文明基础，介绍了开源的相关

- 作者：Eric Raymond （December 4, 1957 (age 59)）

-  [作者介绍](https://en.wikipedia.org/wiki/Eric_S._Raymond)

- [作者个人主页](http://www.catb.org/esr/)

**Comment by violettianjie** [comment]
## 人名卡 Linus Torvalds

- 人名 Linus Torvalds（1969.12.28--） ：出生在芬兰，美国人，软件工程师。Linux 内核的发明者。发明了 [Git](https://en.wikipedia.org/wiki/Git)

- [出处](https://en.wikipedia.org/wiki/Linus_Torvalds)

- 开发风格： release early and often, delegate everything you can, be open to the point of promiscuity
  尽早发布，尽量授权，尽量开放

**Comment by violettianjie** [comment]
## 《大教堂与市集》 金句卡

>  An important trait of the great ones is constructive laziness. They know that you get an A not for effort but for results, and that it's almost always easier to start from a good partial solution than from nothing at all.
    伟大者的一个重要特点是建设性懒惰。他们知道你需要的是结果而不是过程。从一个好的部分方案开始比从0开始要容易得多。

>  Plan to throw one away; you will, anyhow.'' (Fred Brooks, The Mythical Man-Month, Chapter 11) Or, to put it another way, you often don't really understand the problem until after the first time you implement a solution. The second time, maybe you know enough to do it right. So if you want to get it right, be ready to start over at least once . 
   “计划扔掉一个，无论如何你都会扔掉一个的。”

> I'm basically a very lazy person who likes to get credit for things other people actually do. ——Linus Torvalds
    “ 我基本上是一个很懒惰的人，喜欢 在其实是别人做的事情上领取荣誉 ”

> imulated by the prospect of having an ego-satisfying piece of the action, rewarded by the sight of constant (even daily) improvement in their work.

**Comment by violettianjie** [comment]
### 术语卡 C4I3SRT

Command and Control, Communications, Computers, Information,. Intelligence, Infrastructure, Surveillance and Reconnaissance Treatment

**Comment by violettianjie** [comment]
## 术语卡 Intelligence agency
- 出处[维基百科](https://en.wikipedia.org/wiki/Intelligence_agency)

**Comment by violettianjie** [comment]
###  人名卡 吕坤
- 吕坤(1536-1618) 明朝文学家，思想家。字叔简，卑心吾、新吾，自号抱独居土，河南宁陵人。

- 代表作[《呻吟语》](http://www.360doc.com/content/13/0103/08/5950366_257783823.shtml)刊刻于1593（明万历二十一年），时吕坤在山西太原任巡抚。

> 

- 6岁入学启蒙，15岁作《夜气铭》、《招良心诗》。25岁中秀才第一，嘉靖十年(1561年)，26岁中举，万历二年(1574年)，39岁中进士，初为裹垣知县，因政绩卓著，调大同，征授户部主事，历郎中。迁山东参政、山西按察使、陕西右布政使。擢右佥都御史，巡抚山四。居3年，召为左佥都御史。历刑部左、右侍郎。吕坤所至，颇有政绩，深受士民爱戴。历山东参政时，“祟文教，恤孤寡，伸武备，禁邪党，立社学，创冬生院以恤残疾。”有奸人借朝泰山之机，装神弄鬼，诈取人财物，多致殒命。吕坤严惩恶人，杜绝丁奸人残害黎民。巡抚山西时，著有《实政录》，被仕宦奉为楷模。吕坤爱亡民如子弟，视贪官若仇人，所刻《风宪约》、《民务》各款深受称颂。他与沈鲤、郭正域被誉为明万历年间天下“三大贤”。 

### 金句卡

> 深沉厚重，是一等资质； 磊落豪雄，是二等资质；聪明才辨，是三等资质。

- 人格、勇气、能力

**Comment by violettianjie** [comment]
- 术语卡 TETRA
- TETRA（Trans European Trunked Radio – 泛欧集群无线电，现在已改为Terrestrial Trunked Radio – 陆上集群无线电）数字集群通信系统是基于数字时分多址（TDMA）技术的专业移动通信系统，该系统是ETSI（欧洲通信标准协会）为了满足欧洲各国的专业部门对移动通信的需要而设计、制订统一标准的开放性系统。

**Comment by violettianjie** [comment]
基于大数据前世今生的智慧系统大数据解决方案探讨
一 大数据的由来
早在1980年，著名未来学家托夫勒在其所著的《第三次浪潮》中就热情地将“大数据”称颂为 “第三次浪潮的华彩乐章”。《自然》杂志在2008年9月推出了名为“大数据”的封面专栏。从2009年开始“大数据”才成为互联网技术行业中的热门词汇。
最早应用“大数据”的是麦肯锡公司(McKinsey)。
对“大数据”进行收集和分析的设想，来自于世界著名的管理咨询公司麦肯锡公司。麦肯锡公司看到了各种网络平台记录的个人海量信息具备潜在的商业价值，于是投入大量人力物力进行调研，在2011年6月发布了关于“大数据”的报告，该报告对“大数据”的影响、关键技术和应用领域等都进行了详尽的分析。

从百度搜索引擎看，国内“大数据”这个词从2012年才引起关注，之后搜索量便迅猛增长。

二 大数据的定义 
维基百科对“大数据”的解读是：“大数据”(Bigdata)，或称巨量数据、海量数据、大资料，指的是所涉及的数据量规模巨大到无法通过人工，在合理时间内达到截取、管理、处理、并整理成为人类所能解读的信息。

全球数据量猛增，2015年达到7500EB（1EB=1028PB）。IDC预计，未来全球数据总量年增长率将维持在50%左右。
一般而言，当前会涉及到大数据的数据量为 几十TB(万亿字节) 和 几个PB(千万亿字节)。

三 大数据 的特点
维克托·迈尔-舍恩伯格和肯尼斯·克耶编写的《大数据时代》中提出：“大数据”的4V特点：Volume(数据量大)、Velocity(输入和处理速度快)、Variety(数据多样性)、Value(价值密度低)。

四 云计算起源、定义
2006年，27岁的Google高级工程师比西莉亚Christophe Bisciglia第一次向Google CEO Eric E. Schmidt提出“云计算”的思想。
起源：Google公司出资在华盛顿大学搭建一个类似于Google搜索的分布式计算系统，由比西莉亚向华盛顿大学的师生们讲授Google的核心技术：GFS分布式文件系统和MapReduce分布式编程框架。施密特先生采纳了比西莉亚的建议，向华盛顿大学捐赠了40台服务器，比西莉亚定期到华盛顿大学进行授课。
2006年8月9日，Eric E. Schmidt在搜索引擎大会上首次提出“云计算”的概念。
2007年，Amazon推出名为“弹性计算云”的收费服务，供中小软件企业按照需求购买，成为业界第一个提供商业云服务的公司。

Wiki百科中对于云计算的定义：云计算是一种通过Internet以服务的方式提供动态可伸缩的虚拟化的资源的计算模式。

五 云计算与“大数据”

将各种“大数据”的应用比作一辆辆“汽车”，支撑起这些“汽车”运行的“高速公路”就是云计算。最著名的实例就是Google搜索引擎。面对海量Web数据，Google于2006年首先提出云计算的概念。支撑Google内部各种“大数据”应用的，正是Google公司自行研发的云计算服务器。
有了云计算服务器才有了“大数据”应用的价值。
G=f（x）  G 我们的目标，f云计算，x大数据。
可以理解云计算的本质，如下：
1用户消费模式的转变：云计算通过互联网提供软硬件与服务，并由网络浏览器或轻量级终端软件来获取和使用服务。
2商业模式的转变：消费者和企业将从“购买软硬件产品”向“购买信息服务”转变，如同100年前“电”的演变，农场和公司逐渐关闭了自己的发电机，从发电厂购买电力。


六 云计算三种发展路径和落地思路
第一条路：**基于大规模搜索数据处理**。源自于谷歌对大规模数据的处理，谷歌为全球的互联网用户提供同一个服务——搜索，它需要将全世界所有的网站的数据都爬回去，然后做排序和索引，之后再为用户提供搜索服务。可以看到这样的工作需要对海量数据进行处理，谷歌需要把上百万台的服务器整合起来去做排序、索引和查询。
第二条路：**基于超大规模在线交易**。淘宝则发展出来云计算的另一条路径，与谷歌有类似之处，同样需要把很多数据整合起来做一件事情。淘宝做的事情是交易。承载6亿用户在线访问和下单支付。因为这是有极其严格的业务要求的，虽然在规模上而言淘宝用不了像谷歌那样多达百万台的机器，但是这也是一个聚沙成塔的过程，把众多的廉价的服务器整合起来去做一件事情，是云计算的第二条路径。
第三条路：**赋闲服务器资源化、虚拟化**。源于在过去的十几年间企业内部在硬件方面进行的大量投资，造成大量赋闲服务器资源。对于企业内部的使场景而言，往往仅有几千或者几万个用户，即便是大型的国有企业拥有有上百万用户，也就仅此而已。和动辄上千万，上亿的互联网用户相比，企业投入大量的IT资源特别是硬件资源的情况下，服务的客户数过少，显然造成服务器资源的赋闲。面对由此造成的资源利用率低的情况，带来的挑战就是如何更多更好地去利用这些赋闲资源。虚拟化技术，最早是IBM在小型机上或者大型机上就实现了，通过虚拟化或者分区技术，可以来解决资源利用率低的问题，虚拟化的技术后来被VMWare发扬光大，在X86的平台上进行了广泛传播应用。
云计算经过发展最终沉淀下来的这些技术，对于任何一个开展的业务而言，都必不可少的。既需要有效利用资源，将规模从小变大；也需要面向客户和业务做在线并且有业务质量保证的交易，同时也需要对数据进行大规模处理，进而产生对数据的洞察来支持业务的智能化。

七   公安业务为什么需要大数据和云计算？
     1 数据量猛增
     2 数据检索，研判需要
     3 进一步人工智能分析等
基于整个大数据平台之上，未来的发展方向是人工智能。


八   从阿里云的发展看大数据涉及的技术 
能够把云计算的三个方向整合到一起的一个方向是大数据的处理。阿里云的大数据处理也是经过了从2009年到2013年这五年的孵化，在2009年的时候，阿里云还是亚洲最大的Oracle集群，但是还是已经无法承载飞速发展的业务。
于是选择了3条分支路径去探索后面的路，第一条路径是用商业的Greenplum（Greenplum was a big data analytics company headquartered in San Mateo, California. Greenplum was acquired by EMC Corporation in July 2010.[1]）来替代分析型数据运算；第二条路是也使用Hadoop做类似的事情；第三件事情，启动了飞天操作系统的研发，目标是打造一个属于自己的大数据平台。
到2010年的时候，Greenplum这条路因为规模和可用性的问题以及计算准确性问题被放弃；2013年的时候，Hadoop平台也因为数据中心规模扩展不上去和安全管理以及权限管理和资源管理等一系列问题，最后不得不放弃这套体系。

 
  
九 	云计算分类
 

十 上云的难点

第一，陷入虚拟化的误区：将虚拟化等同于云计算，沿着虚拟化的这条路走到黑。
第二，缺乏数据中心全局方案：在小规模的应用场景下，进行简单的虚拟化还是可行的，但是当云变成了公共资产，变成一个平台的时候，就需要从大规模的角度甚至从数据中心整体的角度考虑，不光要考虑硬件的安装部署，还要考虑后续的维护和统筹部署，安全问题以及业务快速响应问题。由于缺乏全局方案，所以数据中心变得非常棘手。
第三，难以全面拥抱公共云：
考虑到公共安全的因素。

十一：ZH系统 大数据的定位（建议）：

1 平台即服务PaaS+软件即服务SaaS。与IaaS厂家（基础架构）合作。针对行业 业务需求，提供特色解决方案。
2 分步骤为公安客户部署大数据方案。从通过Hbase 去Oracle 开始第一阶段。
3 公有云和私有云结合，提高客户资源利用率，节约成本。

十二 合作生态链

**Comment by violettianjie** [comment]
What Is Apache Hadoop?
The Apache™ Hadoop® project develops open-source software for reliable, scalable, distributed computing. 
The Apache Hadoop software library is a framework that allows for the distributed processing of large data sets across clusters of computers using simple programming models. It is designed to scale up from single servers to thousands of machines, each offering local computation and storage. Rather than rely on hardware to deliver high-availability, the library itself is designed to detect and handle failures at the application layer, so delivering a highly-available service on top of a cluster of computers, each of which may be prone to failures. 
The project includes these modules: 
•	Hadoop Common: The common utilities that support the other Hadoop modules. 
•	Hadoop Distributed File System (HDFS™): A distributed file system that provides high-throughput access to application data.
•	Hadoop YARN: A framework for job scheduling and cluster resource management.
•	Hadoop MapReduce: A YARN-based system for parallel processing of large data sets.
Other Hadoop-related projects at Apache include:
•	Ambari™: A web-based tool for provisioning, managing, and monitoring Apache Hadoop clusters which includes support for Hadoop HDFS, Hadoop MapReduce, Hive, HCatalog, HBase, ZooKeeper, Oozie, Pig and Sqoop. Ambari also provides a dashboard for viewing cluster health such as heatmaps and ability to view MapReduce, Pig and Hive applications visually alongwith features to diagnose their performance characteristics in a user-friendly manner.
•	Avro™: A data serialization system.
•	Cassandra™: A scalable multi-master database with no single points of failure.
•	Chukwa™: A data collection system for managing large distributed systems. 
•	HBase™: A scalable, distributed database that supports structured data storage for large tables. 
•	Hive™: A data warehouse infrastructure that provides data summarization and ad hoc querying. 
•	Mahout™: A Scalable machine learning and data mining library. 
•	Pig™: A high-level data-flow language and execution framework for parallel computation.
•	Spark™: A fast and general compute engine for Hadoop data. Spark provides a simple and expressive programming model that supports a wide range of applications, including ETL, machine learning, stream processing, and graph computation.
•	Tez™: A generalized data-flow programming framework, built on Hadoop YARN, which provides a powerful and flexible engine to execute an arbitrary DAG of tasks to process data for both batch and interactive use-cases. Tez is being adopted by Hive™, Pig™ and other frameworks in the Hadoop ecosystem, and also by other commercial software (e.g. ETL tools), to replace Hadoop™ MapReduce as the underlying execution engine.
•	ZooKeeper™: A high-performance coordination service for distributed applications.

**Comment by violettianjie** [comment]
上一段工作辞职，这个issue 先关闭。人生一个小小阶段的结束。下半年新的开始。
