### ISSUE TITLE
认知写作课4期

### ISSUE THREAD

**Issue by violettianjie** [violettianjie/hello-world#5]
## 人名卡 

- 人名  Ted Chiang （美籍华裔，1967--），Chiang Feng-nan (姜峯楠).

- 经历：出生在纽约，父母都是中国人，从台湾移民到美国
-  科幻作家:His work has (as of 2013) won four Nebula awards星云奖, four Hugo awards雨果奖, the John W. Campbell Award for Best New Writer, and four Locus awards.

- 主要作品 ：Tower of Babylon (1990)、[Story of Your Life](https://en.wikipedia.org/wiki/Story_of_Your_Life) (1998)、Stories of Your Life and Others (2002)

- 出处[维基](https://en.wikipedia.org/wiki/Ted_Chiang)

- 《你的生命故事》2016年改变成电影 arrival[到达](https://en.wikipedia.org/wiki/Arrival_(film))

**Comment by violettianjie** [comment]
## 金句卡

> 所谓美文(belleslettres)，是指不带实用目的专供直觉观赏的作品。反之，带有实用目的之写作，例如新闻、公文、论述之类，或可笼统称为杂文。美文重感性，长于抒情，由作家来写。杂文重知性，长于达意，凡知识分子都可以执笔。不过两者并非截然可分，因为杂文写好了，可以当美文来欣赏，而美文也往往为实用目的而作。 —— 余光中

**Comment by sarahpong** [comment]
谢谢附上学习卡片！金句卡里，余光中先生对美文的定义让我想起了之前英语课上的一篇文章，叫Between Solitude and Loneliness，作者是一位美国诗人，他的文章或许不具实用功能，但其用词、叙述方式生动，细腻，优美，易让读者产生共鸣，例如，文中harbour这个动词令我印象深刻，还有像“We lived together and we grew apart.”这样的句子，together与apart对仗，连词用and而非but。也许这就属于余先生所说的美文范畴吧。

**Comment by violettianjie** [comment]
@sarahpong  

> We lived together and we grew apart.  

很美。谢谢分享。

**Comment by violettianjie** [comment]
## 金句卡

苏东坡说的人生赏心十六件乐事：

> 清溪浅水行舟；微雨竹窗夜话；暑至临溪濯足；雨后登楼看山；柳荫堤畔闲行；花坞樽前微笑；隔江山寺闻钟；月下东邻吹箫；晨兴半柱茗香；午倦一方藤枕；开瓮勿逢陶谢；接客不着衣冠；乞得名花盛开；飞来家禽自语；客至汲泉烹茶；抚琴听者知音

**Comment by Fwmns** [comment]
直觉观赏之美文，实用目的之杂文。写好之后，美文可带杂文之实，杂文亦有美文之无用之美。

**Comment by violettianjie** [comment]
@Fwmns 到一定阶段或境界，美文杂文可以交相辉映，如同古人写的优美的寻物启示。希望有一日自己也可以达到这样的境界。
