### ISSUE TITLE
高阶模型及应用

### ISSUE THREAD

**Issue by violettianjie** [violettianjie/hello-world#9]
## 高阶模型：必要难度（desirable difficulty）

- 提出者：罗伯特.艾伦.比约克 （Rorbert Allen Bjork) (1939——）斯坦福大学博士，加利福利亚大学心理学杰出教授（ Distinguished Professor ）。

- 领域：human learning and memory and on the implications of the science of learning for instruction and training. 

- 概念：1994年提出必要难度理论。

- [出处：](https://en.wikipedia.org/wiki/Robert_A._Bjork)

- 印象：学习后改变时空背景，再做笔记
              时间间隔，增加必要难度
              地点转行，增加必要难度
              多主题交错学习
              用输出代替输入，增加必要难度
              用自己的话/测试，增加必要难度

- 应用： 通识部落读书卡片

- 应用： （反） 坏习惯要避免： 读后直接照抄原文，1、2、3清单式的读书笔记。

**Comment by violettianjie** [comment]
## 高阶模型： 第二序改变（Sencond Order Change）

- 提出者：克里斯. 阿吉里斯（Chris Argyris） （1923-2013）美国商业理论家，美国哈佛商学院荣誉教授

- 领域：Action Science 行动科学 organization development、learning organizations.

-概念：系统本身发生了改变

- [出处：](https://en.wikipedia.org/wiki/Chris_Argyris)《改变》

- 印象：跳出系统之外，去解决问题 
      
- 应用：不想为什么，而想是什么？
              思考时多问几个“为什么”，行动时多想一些“是什么”
              > 尝试去训练自己捕捉某个互动的过程，回想关系脉络中发生了“什么”及“如何”发生，而不是事后自以为是地去解释“为什么”。

             处理此时此地的情境，直接处理问题的结果而不是探究问题发生的假设性愿因
             让问题情境超脱尝试解决问题时掉入的悖论陷阱，置于不同的解决问题框架之中

- 应用：（反）坏习惯要避免：事后问为什么时，大脑的认知陷阱合理化自己之前的错误选择，从而放弃主观努力和改变。

**Comment by violettianjie** [comment]
## 高阶模型：有限理性（Bounded Rationality)

- 提出者：西蒙（Herbert Simon）（1916-2001）美国政治学家，经济学家，社会学家，心理学家。，计算机科学家。1978年获诺贝尔经济学奖。

- 领域：decision-making

- [出处](https://en.wikipedia.org/wiki/Herbert_A._Simon)：1982年提出

- 印象：认为人的理性是处于完全理性和完全非理性之间的一种状态。不是追求完美而是追求满意。

- 应用：基于有限理性去决策。不用对自己的现状追求完美，而是追求满意的赢家脚本。

- 应用（反）：过于追求完美。比如并没有承诺永不离职，辞职后认为是输家，而实际上并不是输家。

**Comment by violettianjie** [comment]
## 高阶模型： 邓巴数

- 提出者： 邓巴：英国进化心理学家

- 领域：进化心理学

- 出处：《进化心理学》 ：每个人核心的朋友圈5人，再外15人，好朋友（50人），朋友（150人）认识的人（500人）

- 印象： 对于最亲密的5人应该花更多的时间。

- 应用： 父母对人生脚本的影响，是2/5.把握好其他3/5的亲密关系的选择和许可，对于改变人生脚本很重要。也是为什么 降低人生复杂度的关键之一是找个好伴侣的解释之一。

- 应用（反）：如果单身或没有其他亲密好友。父母2/5的影响可能变成5/5 ，会非常巨大。

**Comment by violettianjie** [comment]
## 高阶模型：自我决定论（Self-Determination Theory,SDT）

- 提出者：美国心理学家Deci Edward L.(德西)和Ryan Richard M.(莱恩)等人在1975年提出的一种关于人类自我决定行为的动机过程理论。
        德西在2012年的TEDxFlourCity活动上做了一次演讲。
- 领域：

- [出处：](http://www.selfdeterminationtheory.org/)

- 印象：内在动机：自主、胜任、归属

- 应用：基于内在动机去决策，改变人生脚本为赢家脚本，允许自己的英雄之旅。

- 应用（反）： 工作外在动机，生活／下班后内在动机，人的心力资源不够。

**Comment by violettianjie** [comment]
《人生脚本》成书于认知科学和认知神经学诞生之前，书中内容用新的观点理解是更好的角度。

1 PAC 三种心理状态用斯坦诺维奇的三重心智，基因模因理解。
 自主心智、算法心智、反省心智。

 成人。       儿童。  父母。

2 游戏、双向沟通等用日常生活中的自我呈现，面子理论来理解。

？
3 各种话语分析和父母的不良影响，用镜像神经元来理解。

？

**Comment by violettianjie** [comment]
## 你的人生脚本如何改写？

###  人生脚本、输家、赢家的定义

- 人生脚本： 
  > 每个人在幼年时就决定了自己将如何生活，如何死亡。无论走到哪里，他都会在头脑中把这个计划带到那里。

 > 脚本符合的条件： 1） 父母的指令 2） 在指令下的人格发展 3） 童年时期的决定 4）总是以某种特定的方法成功或失败 5）确信的态度（当下对过去的事坚信不移）
  
 >  多数情况下，人们将人生花在了欺骗世界上，而且通常也包括欺骗自己。
 
一个真正的人的定义：他能够自发地以理性的和让人信赖的方式做事，并能够适当地考虑他人的需要。


> 赢家：实现了与世界、与自己所订契约的人。即 他打算做某事，承诺做某事，从长远的角度，确实做到了。


### 五大高阶模型回顾



### 将高阶模型应用于人生脚本的修正

## 高阶模型： 第二序改变（Sencond Order Change）

- 提出者：克里斯. 阿吉里斯（Chris Argyris） （1923-2013）美国商业理论家，美国哈佛商学院荣誉教授

- 领域：Action Science 行动科学 organization development、learning organizations.

-概念：系统本身发生了改变

- [出处：](https://en.wikipedia.org/wiki/Chris_Argyris)《改变》

- 印象：跳出系统之外，去解决问题 
      
- 应用：不想为什么，而想是什么？
              思考时多问几个“为什么”，行动时多想一些“是什么”
              > 尝试去训练自己捕捉某个互动的过程，回想关系脉络中发生了“什么”及“如何”发生，而不是事后自以为是地去解释“为什么”。

             处理此时此地的情境，直接处理问题的结果而不是探究问题发生的假设性愿因
             让问题情境超脱尝试解决问题时掉入的悖论陷阱，置于不同的解决问题框架之中

- 应用：（反）坏习惯要避免：事后问为什么时，大脑的认知陷阱合理化自己之前的错误选择，从而放弃主观努力和改变。


## 高阶模型：有限理性（Bounded Rationality)

- 提出者：西蒙（Herbert Simon）（1916-2001）美国政治学家，经济学家，社会学家，心理学家。，计算机科学家。1978年获诺贝尔经济学奖。

- 领域：decision-making

- [出处](https://en.wikipedia.org/wiki/Herbert_A._Simon)：1982年提出

- 印象：认为人的理性是处于完全理性和完全非理性之间的一种状态。不是追求完美而是追求满意。

- 应用：基于有限理性去决策。不用对自己的现状追求完美，而是追求满意的赢家脚本。

- 应用（反）：过于追求完美。比如并没有承诺永不离职，辞职后认为是输家，而实际上并不是输家。

## 高阶模型： 邓巴数

- 提出者： 邓巴：英国进化心理学家

- 领域：进化心理学

- 出处：《人类的演化》 ：每个人核心的朋友圈5人，再外15人，好朋友（50人），朋友（150人）认识的人（500人）

- 印象： 对于最亲密的5人应该花更多的时间。

- 应用： 父母对人生脚本的影响，是2/5.把握好其他3/5的亲密关系的选择和许可，对于改变人生脚本很重要。也是为什么 降低人生复杂度的关键之一是找个好伴侣的解释之一。

- 应用（反）：如果单身或没有其他亲密好友。父母2/5的影响可能变成5/5 ，会非常巨大。


## 高阶模型：自我决定论（Self-Determination Theory,SDT）

- 提出者：美国心理学家[Edward L. Deci](https://en.wikipedia.org/wiki/Edward_L._Deci)(德西1942——)和Ryan Richard M.(莱恩)等人在1975年提出的一种关于人类自我决定行为的动机过程理论。
        德西在2012年的TEDxFlourCity活动上做了一次演讲。

- 领域：人类动机

- [出处：](http://www.selfdeterminationtheory.org/)

- 印象：内在动机：自主、胜任、归属。 

             控制的动机 Controlled Mmotivation vs 自主的动机 Autonomous Motivation

- 应用：基于内在动机去决策，改变人生脚本为赢家脚本，允许自己的英雄之旅。

  对他人：autonomy support 自主的支持： 不要问你如何能给予别人内在动机，问你如何创造一个环境，在其中他们能够找到自己的内在动？

- 应用（反）： 工作外在动机，生活／下班后内在动机，人的心力资源不够。

### 踏上你我的英雄之旅

承认自己的有限理性，父母的影响，同时给自己以允许，找到自己的内在动机，进行第二序改变，踏上自己的英雄之旅。


### 参考资料

**Comment by heshenxian1** [comment]
棒，👍。从有限理性和满意论，想起阳老有篇文章说人生70分就好。谈到许可和改变，联想到从经济学看人生成本，历史成本不是成本，沉没成本不是成本。一切成本都是机会成本，成本永远向前看。

**Comment by luyutong** [comment]
:+1: 
遇见自己，悦纳自己，做自己生命中的贵人。
谢谢你，你的思考与行动亦是照亮世界的光，温暖了我。

**Comment by violettianjie** [comment]
@heshenxian1  谢谢夸奖，被夸奖的感觉很好，很受鼓舞。你说的经济学看人生成本，机会成本又是一个新的角度，引发新的思考......

@luyutong 谢谢你的回复，共同努力，共同进步。照亮彼此，温暖世界，感谢有你。
